require("user.impatient")
require("user.options")
require("user.plugins")
require("user.autocommands")
require("user.keymaps")
require("user.cmp")
require("user.lsp")
require("user.dap")
require("user.ext")
require("user.ui")

